{% set name = "flyteidl" %}
{% set version = "1.13.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flyteidl-{{ version }}.tar.gz
  sha256: 5bc546500e559ddc08c233bdc20d223b12c07a0ae1ee1aa46c0c131531c3155c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    # The dependencies below are required to make sure `setuptools_scm` is used to 
    # dynamically infer the version. Without this, the `pip` version of the package
    # would appear to be 0.0.0
    - setuptools >=69
    - setuptools_scm >=8
    - toml
  run:
    - python >=3.8
    - googleapis-common-protos
    - protoc-gen-openapiv2
    - protobuf >=4.21.1,<5.0.0

test:
  imports:
    - flyteidl
    - flyteidl.admin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/flyteorg/flyteidl
  summary: IDL for Flyte Platform
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    This is one of the core repositories of Flyte. It contains the Specification 
    of the Flyte Language using protobuf messages, the Backend API specification 
    in gRPC, and Swagger REST. The repo contains the generated clients and protocol 
    message structures in multiple languages. Along with the generated code, the 
    repository also contains the Golang clients for Flyte's backend APIs (the 
    services grouped under FlyteAdmin).

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flyteidl/](https://pypi.org/project/flyteidl/)

  doc_url: https://docs.flyte.org/projects/flyteidl/en/stable/
  dev_url: https://github.com/flyteorg/flyteidl

extra:
  recipe-maintainers:
    - bstadlbauer
    - bmcconeghy
    - asford
    - sugatoray
    - eapolinario
    - cosmicBboy
