{% set name = "flyteidl" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flyteidl-{{ version }}.tar.gz
  sha256: 7af316bc63a9079852e7b732f9a63c950babe1bf0e7c899deb013092fe8feade

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    # The dependencies below are required to make sure `setuptools_scm` is used to 
    # dynamically infer the version. Without this, the `pip` version of the package
    # would appear to be 0.0.0
    - setuptools >=69
    - setuptools_scm >=8
    - toml
  run:
    - python >={{ python_min }}
    - googleapis-common-protos
    - protoc-gen-openapiv2
    - protobuf >=4.21.1,<5.0.0

test:
  imports:
    - flyteidl
    - flyteidl.admin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.github.com/flyteorg/flyteidl
  summary: IDL for Flyte Platform
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    This is one of the core repositories of Flyte. It contains the Specification 
    of the Flyte Language using protobuf messages, the Backend API specification 
    in gRPC, and Swagger REST. The repo contains the generated clients and protocol 
    message structures in multiple languages. Along with the generated code, the 
    repository also contains the Golang clients for Flyte's backend APIs (the 
    services grouped under FlyteAdmin).

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flyteidl/](https://pypi.org/project/flyteidl/)

  doc_url: https://docs.flyte.org/projects/flyteidl/en/stable/
  dev_url: https://github.com/flyteorg/flyteidl

extra:
  recipe-maintainers:
    - bstadlbauer
    - bmcconeghy
    - asford
    - sugatoray
    - eapolinario
    - cosmicBboy
