{% set name = "flyteidl" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flyteidl-{{ version }}.tar.gz
  sha256: 6452516f9925f248cc1a77ff8ae246841d276595b5e87a27754e01e3d32b0d13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - protobuf >=3.5.0,<4.0.0
    - python >=3.6

test:
  imports:
    - flyteidl
    - flyteidl.core.tasks_pb2
    - validate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/flyteorg/flyteidl
  summary: IDL for Flyte Platform
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - bmcconeghy
    - asford
